#!/usr/bin/env bash

set -u
actuallyStatAndExit () {
    $1/$actualStatter
    exit $?
}

actualStatter=statmygits
[[ -x ~/bin/$actualStatter ]] && actuallyStatAndExit ~/bin

myDir=$(dirname $0)
cd $myDir || { echo "Cannot get to my ${myDir}, exiting."; exit 1; }
[[ -x ./$actualStatter ]] && actuallyStatAndExit .

echo "Very odd, we shouldn't have gotten here."
exit 1

